services:
  app:
    image: summerbeachhh/ctf-platform:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/ctf_platform?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /vol1/docker/volumes/ctf/uploads:/app/uploads
      - /vol1/docker/volumes/ctf/cache:/app/cache

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=ctf_platform
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
    volumes:
      - /vol1/docker/volumes/ctf/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5
